Repository openshift/service-ca-operator, pull requests merged in 2019-03, with the labels that each got.

#23 OpenAPIV3 validation for operator CRD
  manifests/0000_09_service-ca-operator_02_crd.yaml
Labels: lgtm, size/M

#24 Honor beta SSCS annotations
  pkg/controller/api/api.go
  pkg/controller/apiservicecabundle/controller/apiservice_cabundle_controller_test.go
  pkg/controller/configmapcainjector/controller/configmap_injecting_controller_test.go
  pkg/controller/servingcert/controller/secret_creating_controller.go
  pkg/controller/servingcert/controller/secret_creating_controller_test.go
  pkg/controller/servingcert/controller/secret_updating_controller.go
  pkg/controller/servingcert/controller/secret_updating_controller_test.go
  test/e2e/e2e_test.go
Labels: lgtm, size/XXL

#27 refactor(bindata,sync): update configmap key to 'ca-bundle.crt'
  bindata/v4.0.0/apiservice-cabundle-controller/defaultconfig.yaml
  bindata/v4.0.0/apiservice-cabundle-controller/signing-cabundle.yaml
  bindata/v4.0.0/configmap-cabundle-controller/defaultconfig.yaml
  bindata/v4.0.0/configmap-cabundle-controller/signing-cabundle.yaml
  pkg/operator/sync_apiservice_v4_00.go
  pkg/operator/sync_configmapcabundle_v4_00.go
  pkg/operator/v4_00_assets/bindata.go
Labels: lgtm, size/S

#29 replace openshift-service-cert-signer with openshift-service-ca
  bindata/v4.0.0/apiservice-cabundle-controller/clusterrolebinding.yaml
  bindata/v4.0.0/apiservice-cabundle-controller/cm.yaml
  bindata/v4.0.0/apiservice-cabundle-controller/deployment.yaml
  bindata/v4.0.0/apiservice-cabundle-controller/ns.yaml
  bindata/v4.0.0/apiservice-cabundle-controller/role.yaml
  bindata/v4.0.0/apiservice-cabundle-controller/rolebinding.yaml
  bindata/v4.0.0/apiservice-cabundle-controller/sa.yaml
  bindata/v4.0.0/apiservice-cabundle-controller/signing-cabundle.yaml
  bindata/v4.0.0/configmap-cabundle-controller/clusterrolebinding.yaml
  bindata/v4.0.0/configmap-cabundle-controller/cm.yaml
  bindata/v4.0.0/configmap-cabundle-controller/deployment.yaml
  bindata/v4.0.0/configmap-cabundle-controller/ns.yaml
  bindata/v4.0.0/configmap-cabundle-controller/role.yaml
  bindata/v4.0.0/configmap-cabundle-controller/rolebinding.yaml
  bindata/v4.0.0/configmap-cabundle-controller/sa.yaml
  bindata/v4.0.0/configmap-cabundle-controller/signing-cabundle.yaml
  bindata/v4.0.0/service-serving-cert-signer-controller/clusterrolebinding.yaml
  bindata/v4.0.0/service-serving-cert-signer-controller/cm.yaml
  bindata/v4.0.0/service-serving-cert-signer-controller/deployment.yaml
  bindata/v4.0.0/service-serving-cert-signer-controller/ns.yaml
  bindata/v4.0.0/service-serving-cert-signer-controller/role.yaml
  bindata/v4.0.0/service-serving-cert-signer-controller/rolebinding.yaml
  bindata/v4.0.0/service-serving-cert-signer-controller/sa.yaml
  bindata/v4.0.0/service-serving-cert-signer-controller/signing-secret.yaml
  pkg/cmd/apiservicecabundle/cmd.go
  pkg/cmd/configmapcabundle/cmd.go
  pkg/cmd/servingcertsigner/cmd.go
  pkg/operator/operatorclient/interfaces.go
  pkg/operator/v4_00_assets/bindata.go
  test/e2e/e2e_test.go
Labels: lgtm, size/L

#28 e2e: Fix operator pod prefix
  test/e2e/e2e_test.go
Labels: lgtm, size/S

#32 manifests: Rename origin-service-ca -> origin-service-ca-operator
  manifests/0000_09_service-ca-operator_05_deploy.yaml
  manifests/image-references
Labels: approved, lgtm, size/XS

#34 Add version, status to operator
  manifests/0000_09_service-ca-operator_05_deploy.yaml
  manifests/0000_09_service-ca-operator_07_clusteroperator.yaml
  pkg/apis/serviceca/install.go
  pkg/apis/serviceca/v1/doc.go
  pkg/apis/serviceca/v1/register.go
  pkg/apis/serviceca/v1/types.go
  pkg/apis/serviceca/v1/types_apiv1copy.go
  pkg/apis/serviceca/v1/zz_generated.deepcopy.go
  pkg/generated/clientset/versioned/clientset.go
  pkg/generated/clientset/versioned/doc.go
  pkg/generated/clientset/versioned/fake/clientset_generated.go
  pkg/generated/clientset/versioned/fake/doc.go
  pkg/generated/clientset/versioned/fake/register.go
  pkg/generated/clientset/versioned/scheme/doc.go
  pkg/generated/clientset/versioned/scheme/register.go
  pkg/generated/clientset/versioned/typed/serviceca/v1/doc.go
  pkg/generated/clientset/versioned/typed/serviceca/v1/fake/doc.go
  pkg/generated/clientset/versioned/typed/serviceca/v1/fake/fake_serviceca.go
  pkg/generated/clientset/versioned/typed/serviceca/v1/fake/fake_serviceca_client.go
  pkg/generated/clientset/versioned/typed/serviceca/v1/generated_expansion.go
  pkg/generated/clientset/versioned/typed/serviceca/v1/serviceca.go
  pkg/generated/clientset/versioned/typed/serviceca/v1/serviceca_client.go
  pkg/generated/informers/externalversions/factory.go
  pkg/generated/informers/externalversions/generic.go
  pkg/generated/informers/externalversions/internalinterfaces/factory_interfaces.go
  pkg/generated/informers/externalversions/serviceca/interface.go
  pkg/generated/informers/externalversions/serviceca/v1/interface.go
  pkg/generated/informers/externalversions/serviceca/v1/serviceca.go
  pkg/generated/listers/serviceca/v1/expansion_generated.go
  pkg/generated/listers/serviceca/v1/serviceca.go
  pkg/operator/operator.go
  pkg/operator/starter.go
  pkg/operator/status.go
  pkg/operator/sync_all_v4_00.go
  pkg/operator/sync_apiservice_v4_00.go
  pkg/operator/sync_configmapcabundle_v4_00.go
  pkg/operator/sync_signer_v4_00.go
  pkg/operator/v4_00_assets/bindata.go
Labels: lgtm, size/XXL

#30 Refactor sync functions
  pkg/operator/operator.go
  pkg/operator/sync.go
  pkg/operator/sync_all_v4_00.go
  pkg/operator/sync_apiservice_v4_00.go
  pkg/operator/sync_common.go
  pkg/operator/sync_configmapcabundle_v4_00.go
  pkg/operator/sync_signer_v4_00.go
Labels: lgtm, size/XL

#39 Fix ERROR: logging before flag.Parse
  cmd/service-ca-operator/main.go
Labels: lgtm, size/XS
