Repository openshift/service-ca-operator, pull requests merged in 2019-11, with the labels that each got.

#82 Bug 1769793: Use openshift/api vendored config CRD
  Dockerfile
  Dockerfile.rhel7
  Makefile
  manifests/02_crd.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#76 status: do not flap degraded from false to unknown
  pkg/operator/operator.go
Labels: approved, lgtm, size/XS

#83 Revert the removal of the service CA from serving certs
  pkg/controller/api/api.go
  pkg/controller/servingcert/controller/secret_creating_controller.go
Labels: approved, lgtm, size/S

#84 Disable automatic CA rotation for now
  pkg/operator/config.go
  pkg/operator/rotate.go
  pkg/operator/rotate_test.go
  test/e2e/e2e_test.go
Labels: approved, lgtm, size/L

#81 Enable Auth for the metrics endpoints for the controllers
  bindata/v4.0.0/apiservice-cabundle-controller/clusterrole.yaml
  bindata/v4.0.0/apiservice-cabundle-controller/defaultconfig.yaml
  bindata/v4.0.0/configmap-cabundle-controller/defaultconfig.yaml
  bindata/v4.0.0/service-serving-cert-signer-controller/clusterrole.yaml
  bindata/v4.0.0/service-serving-cert-signer-controller/defaultconfig.yaml
  pkg/operator/v4_00_assets/bindata.go
Labels: approved, lgtm, size/M
