Repository openshift/service-ca-operator, pull requests merged in 2019-08, with the labels that each got.

#66 Bug 1740121: Make service-ca have guaranteed scheduling
  bindata/v4.0.0/apiservice-cabundle-controller/deployment.yaml
  bindata/v4.0.0/configmap-cabundle-controller/deployment.yaml
  bindata/v4.0.0/service-serving-cert-signer-controller/deployment.yaml
  hack/verify-generated-bindata.sh
  manifests/05_deploy.yaml
  pkg/operator/v4_00_assets/bindata.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#69 update Dockerfile, Dockerfile.rhel7 ldflags, update Makefile make images
  Dockerfile
  Dockerfile.rhel7
  Makefile
Labels: approved, lgtm, size/M

#70 Update OWNERS
  OWNERS
Labels: approved, lgtm, size/XS
