Repository openshift/service-ca-operator, pull requests merged in 2019-04, with the labels that each got.

#26 Bug 1683058: Prevent sharing of configmap and secret data
  pkg/controller/configmapcainjector/controller/configmap_injecting_controller.go
  pkg/controller/configmapcainjector/controller/configmap_injecting_controller_test.go
  pkg/controller/servingcert/controller/secret_creating_controller.go
  pkg/controller/servingcert/controller/secret_updating_controller.go
  pkg/controller/servingcert/controller/secret_updating_controller_test.go
  test/e2e/e2e_test.go
Labels: lgtm, size/XL

#38 Allow deletion of signing key secret for CA regeneration
  bindata/v4.0.0/apiservice-cabundle-controller/defaultconfig.yaml
  bindata/v4.0.0/configmap-cabundle-controller/defaultconfig.yaml
  bindata/v4.0.0/service-serving-cert-signer-controller/defaultconfig.yaml
  pkg/boilerplate/controller/filter.go
  pkg/controller/configmapcainjector/controller/configmap_injecting_controller.go
  pkg/controller/servingcert/controller/secret_creating_controller.go
  pkg/controller/servingcert/controller/secret_creating_controller_test.go
  pkg/operator/sync.go
  pkg/operator/sync_common.go
  pkg/operator/v4_00_assets/bindata.go
  test/e2e/e2e_test.go
Labels: lgtm, size/XL

#37 Improve/fix version,status reporting for service-ca clusteroperator
  pkg/operator/operator.go
  pkg/operator/operatorclient/operatorclient.go
  pkg/operator/starter.go
  pkg/operator/status.go
Labels: lgtm, size/L

#44 Bug 1700037: Check cert issuer directly
  pkg/controller/servingcert/controller/secret_creating_controller.go
  pkg/controller/servingcert/controller/secret_creating_controller_test.go
Labels: lgtm, size/L

#45 Bug 1664421: remove emoji from event logs
  pkg/boilerplate/operator/option.go
Labels: lgtm, size/XS

#47 Use CVO for operator config
  manifests/0000_09_service-ca-operator_03_operator.cr.yaml
  pkg/operator/starter.go
  pkg/operator/v4_00_assets/bindata.go
Labels: lgtm, size/M

#46 bug 1700903: standardize names for api freeze
  bindata/v4.0.0/apiservice-cabundle-controller/deployment.yaml
  bindata/v4.0.0/configmap-cabundle-controller/deployment.yaml
  bindata/v4.0.0/service-serving-cert-signer-controller/deployment.yaml
  manifests/0000_09_service-ca-operator_00_roles.yaml
  manifests/0000_09_service-ca-operator_03_cm.yaml
  manifests/0000_09_service-ca-operator_04_sa.yaml
  manifests/0000_09_service-ca-operator_05_deploy.yaml
  pkg/cmd/apiservicecabundle/cmd.go
  pkg/cmd/configmapcabundle/cmd.go
  pkg/cmd/operator/cmd.go
  pkg/cmd/servingcertsigner/cmd.go
  pkg/operator/operatorclient/interfaces.go
  pkg/operator/v4_00_assets/bindata.go
  test/e2e/e2e_test.go
Labels: lgtm, size/M

#50 Add node-selector annotation to namespace
  bindata/v4.0.0/apiservice-cabundle-controller/ns.yaml
  bindata/v4.0.0/configmap-cabundle-controller/ns.yaml
  bindata/v4.0.0/service-serving-cert-signer-controller/ns.yaml
  manifests/0000_09_service-ca-operator_01_namespace.yaml
  pkg/operator/v4_00_assets/bindata.go
Labels: lgtm, size/S

#52 Move component to an appropriate upgrade order (generic)
  manifests/00_roles.yaml
  manifests/01_namespace.yaml
  manifests/02_crd.yaml
  manifests/03_cm.yaml
  manifests/03_operator.cr.yaml
  manifests/04_sa.yaml
  manifests/05_deploy.yaml
  manifests/06_config.yaml
  manifests/07_clusteroperator.yaml
Labels: approved, lgtm, size/XS

#49 Shorten signing key secret name
  bindata/v4.0.0/service-serving-cert-signer-controller/deployment.yaml
  bindata/v4.0.0/service-serving-cert-signer-controller/signing-secret.yaml
  pkg/controller/api/resourcenames.go
  pkg/operator/v4_00_assets/bindata.go
  test/e2e/e2e_test.go
Labels: lgtm, size/S
