Repository openshift/service-ca-operator, pull requests merged in 2019-05, with the labels that each got.

#54 Enable Auth for metrics endpoint
  manifests/03_cm.yaml
Labels: lgtm, size/XS

#53 README: replace alpha annotations to beta
  README.md
Labels: lgtm, size/S

#56 Fix tolerations
  bindata/v4.0.0/apiservice-cabundle-controller/deployment.yaml
  bindata/v4.0.0/configmap-cabundle-controller/deployment.yaml
  bindata/v4.0.0/service-serving-cert-signer-controller/deployment.yaml
  manifests/05_deploy.yaml
  pkg/operator/v4_00_assets/bindata.go
Labels: lgtm, size/M

#57 bug 1711075: set resource requests on containers
  bindata/v4.0.0/apiservice-cabundle-controller/deployment.yaml
  bindata/v4.0.0/configmap-cabundle-controller/deployment.yaml
  bindata/v4.0.0/service-serving-cert-signer-controller/deployment.yaml
  manifests/05_deploy.yaml
  pkg/operator/v4_00_assets/bindata.go
Labels: lgtm, size/S

#59 README update
  README.md
Labels: lgtm, size/XS
