Repository openshift/service-ca-operator, pull requests merged in 2019-02, with the labels that each got.

#19 feat(operator): sync operator status
  pkg/operator/operatorclient/operatorclient.go
  pkg/operator/starter.go
Labels: lgtm, size/L

#18 Make the signing CA last 1 year
  pkg/operator/sync_signer_v4_00.go
Labels: lgtm, size/XS

#21 fix(pkg/operator/starter): start sscs informer
  bindata/v4.0.0/apiservice-cabundle-controller/cm.yaml
  bindata/v4.0.0/configmap-cabundle-controller/cm.yaml
  bindata/v4.0.0/service-serving-cert-signer-controller/cm.yaml
  manifests/0000_09_service-ca-operator_03_cm.yaml
  pkg/operator/starter.go
Labels: lgtm, size/S
