Repository openshift/service-ca-operator, pull requests merged in 2020-02, with the labels that each got.

#107 Remove the option to disable automated CA rotation
  pkg/operator/config.go
  pkg/operator/rotate.go
  pkg/operator/rotate_test.go
  test/e2e/e2e_test.go
Labels: approved, lgtm, size/M

#106 Update CA duration to 26 months to ensure upgrade after rotation
  pkg/operator/rotate.go
Labels: approved, lgtm, size/S

#95 Bug 1803282: enable signer ca expiry timer metrics
  pkg/operator/metrics/metrics.go
  pkg/operator/sync_common.go
  test/e2e/e2e_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#104 Bug 1788179: Enable automated rotation for 4.3
  pkg/operator/config.go
  pkg/operator/rotate.go
  pkg/operator/rotate_test.go
  test/e2e/e2e_test.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/L
