Repository openshift/service-ca-operator, pull requests merged in 2020-01, with the labels that each got.

#91 bump builder image to golang-1.13 in dockerfiles
  Dockerfile
  Dockerfile.rhel7
  go.mod
  go.sum
Labels: approved, lgtm, size/S

#90 Configure metrics collection for operator
  go.mod
  go.sum
  manifests/0000_90_service-ca-operator_01_prometheusrole.yaml
  manifests/0000_90_service-ca-operator_02_prometheusrolebinding.yaml
  manifests/0000_90_service-ca-operator_03_servicemonitor.yaml
  manifests/01_namespace.yaml
  manifests/02_service.yaml
  manifests/05_deploy.yaml
  test/e2e/e2e_test.go
  vendor/github.com/openshift/client-go/route/clientset/versioned/clientset.go
  vendor/github.com/openshift/client-go/route/clientset/versioned/doc.go
  vendor/github.com/openshift/client-go/route/clientset/versioned/scheme/doc.go
  vendor/github.com/openshift/client-go/route/clientset/versioned/scheme/register.go
  vendor/github.com/openshift/client-go/route/clientset/versioned/typed/route/v1/doc.go
  vendor/github.com/openshift/client-go/route/clientset/versioned/typed/route/v1/generated_expansion.go
  vendor/github.com/openshift/client-go/route/clientset/versioned/typed/route/v1/route.go
  vendor/github.com/openshift/client-go/route/clientset/versioned/typed/route/v1/route_client.go
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/targets/openshift/deps-gomod.mk
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/core.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/event_helpers.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourcehelper/resource_helpers.go
  vendor/github.com/openshift/library-go/test/library/metrics/query.go
  vendor/github.com/prometheus/client_golang/api/client.go
  vendor/github.com/prometheus/client_golang/api/prometheus/v1/api.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#89 Deploy all controllers as one process
  README.md
  bindata/v4.0.0/apiservice-cabundle-controller/clusterrole.yaml
  bindata/v4.0.0/apiservice-cabundle-controller/clusterrolebinding.yaml
  bindata/v4.0.0/apiservice-cabundle-controller/deployment.yaml
  bindata/v4.0.0/apiservice-cabundle-controller/sa.yaml
  bindata/v4.0.0/configmap-cabundle-controller/clusterrole.yaml
  bindata/v4.0.0/configmap-cabundle-controller/clusterrolebinding.yaml
  bindata/v4.0.0/configmap-cabundle-controller/ns.yaml
  bindata/v4.0.0/configmap-cabundle-controller/role.yaml
  bindata/v4.0.0/configmap-cabundle-controller/rolebinding.yaml
  bindata/v4.0.0/configmap-cabundle-controller/signing-cabundle.yaml
  bindata/v4.0.0/controller/clusterrole.yaml
  bindata/v4.0.0/controller/clusterrolebinding.yaml
  bindata/v4.0.0/controller/deployment.yaml
  bindata/v4.0.0/controller/ns.yaml
  bindata/v4.0.0/controller/role.yaml
  bindata/v4.0.0/controller/rolebinding.yaml
  bindata/v4.0.0/controller/sa.yaml
  bindata/v4.0.0/controller/signing-cabundle.yaml
  bindata/v4.0.0/controller/signing-secret.yaml
  bindata/v4.0.0/service-serving-cert-signer-controller/clusterrole.yaml
  bindata/v4.0.0/service-serving-cert-signer-controller/deployment.yaml
  bindata/v4.0.0/service-serving-cert-signer-controller/ns.yaml
  bindata/v4.0.0/service-serving-cert-signer-controller/role.yaml
  bindata/v4.0.0/service-serving-cert-signer-controller/rolebinding.yaml
  bindata/v4.0.0/service-serving-cert-signer-controller/sa.yaml
  cmd/service-ca-operator/main.go
  pkg/cmd/apiservicecabundle/cmd.go
  pkg/cmd/configmapcabundle/cmd.go
  pkg/cmd/controller/cmd.go
  pkg/cmd/servingcertsigner/cmd.go
  pkg/controller/api/resourcenames.go
  pkg/controller/apiservicecabundle/starter/starter.go
  pkg/controller/configmapcainjector/starter/starter.go
  pkg/controller/servingcert/starter/starter.go
  pkg/controller/starter.go
  pkg/operator/operator.go
  pkg/operator/starter.go
  pkg/operator/sync.go
  pkg/operator/sync_common.go
  pkg/operator/v4_00_assets/bindata.go
  test/e2e/e2e_test.go
Labels: approved, lgtm, size/XXL

#99 Double polling timeout that looks to be failing the rotation tests
  test/e2e/e2e_test.go
Labels: approved, lgtm, size/S

#78 Refactor ca bundle injection for maintainability
  go.mod
  pkg/controller/apiservicecabundle/controller/apiservice_cabundle_controller.go
  pkg/controller/apiservicecabundle/controller/apiservice_cabundle_controller_test.go
  pkg/controller/apiservicecabundle/starter/starter.go
  pkg/controller/cabundleinjector/apiservice.go
  pkg/controller/cabundleinjector/configmap.go
  pkg/controller/cabundleinjector/starter.go
  pkg/controller/configmapcainjector/controller/configmap_injecting_controller.go
  pkg/controller/configmapcainjector/controller/configmap_injecting_controller_test.go
  pkg/controller/configmapcainjector/starter/starter.go
  pkg/controller/starter.go
  pkg/operator/sync_common.go
  test/e2e/e2e_test.go
  vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/fake/clientset_generated.go
  vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/fake/doc.go
  vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/fake/register.go
  vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/typed/apiregistration/v1/fake/doc.go
  vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/typed/apiregistration/v1/fake/fake_apiregistration_client.go
  vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/typed/apiregistration/v1/fake/fake_apiservice.go
  vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/typed/apiregistration/v1beta1/fake/doc.go
  vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/typed/apiregistration/v1beta1/fake/fake_apiregistration_client.go
  vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/typed/apiregistration/v1beta1/fake/fake_apiservice.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#97 Remove unnecessary permissions for controllers
  bindata/v4.0.0/controller/role.yaml
  pkg/operator/v4_00_assets/bindata.go
Labels: approved, lgtm, size/M

#100 Enable injection of service CA bundle for CRDs
  README.md
  bindata/v4.0.0/controller/clusterrole.yaml
  go.mod
  pkg/controller/cabundleinjector/crd.go
  pkg/controller/cabundleinjector/starter.go
  pkg/operator/v4_00_assets/bindata.go
  test/e2e/e2e_test.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/clientset.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1/apiextensions_client.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1/customresourcedefinition.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1/generated_expansion.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/informers/externalversions/apiextensions/interface.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/informers/externalversions/apiextensions/v1/customresourcedefinition.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/informers/externalversions/apiextensions/v1/interface.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/informers/externalversions/apiextensions/v1beta1/customresourcedefinition.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/informers/externalversions/apiextensions/v1beta1/interface.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/informers/externalversions/factory.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/informers/externalversions/generic.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/informers/externalversions/internalinterfaces/factory_interfaces.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/listers/apiextensions/v1/customresourcedefinition.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/listers/apiextensions/v1/expansion_generated.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/listers/apiextensions/v1beta1/customresourcedefinition.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/listers/apiextensions/v1beta1/expansion_generated.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#79 Enable injection of service CA bundle for admission webhooks
  README.md
  bindata/v4.0.0/controller/clusterrole.yaml
  pkg/controller/cabundleinjector/mutatingwebhook.go
  pkg/controller/cabundleinjector/starter.go
  pkg/controller/cabundleinjector/validatingwebhook.go
  pkg/operator/v4_00_assets/bindata.go
  test/e2e/e2e_test.go
Labels: approved, lgtm, size/L

#101 Extend service CA duration to 14 months
  pkg/operator/rotate.go
Labels: approved, lgtm, size/S

#102 Update new bundle injection targets to only support beta annotation
  pkg/controller/api/api.go
  pkg/controller/cabundleinjector/apiservice.go
  pkg/controller/cabundleinjector/configmap.go
  pkg/controller/cabundleinjector/crd.go
  pkg/controller/cabundleinjector/mutatingwebhook.go
  pkg/controller/cabundleinjector/starter.go
  pkg/controller/cabundleinjector/validatingwebhook.go
Labels: approved, lgtm, size/M

#103 Fix CA bundle annotation check to be case-insensitive
  pkg/controller/cabundleinjector/starter.go
Labels: approved, lgtm, size/XS

#98 e2e test to check service serving cert using client pod
  test/e2e/e2e_test.go
Labels: approved, lgtm, size/L
