Repository openshift/service-ca-operator, pull requests merged in 2021-07, with the labels that each got.

#167 bug 1981498: add vulnerable legacy injector to allow for upgrade clusters to use ...
  pkg/controller/api/api.go
  pkg/controller/cabundleinjector/configmap.go
  pkg/controller/cabundleinjector/starter.go
  test/e2e/e2e_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#170 [release-4.7] bug 1981634: add vulnerable legacy injector to allow for upgrade clusters to use
  pkg/controller/api/api.go
  pkg/controller/cabundleinjector/configmap.go
  pkg/controller/cabundleinjector/starter.go
  test/e2e/e2e_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#163 Add s-urbaniak, remove marun from OWNERS
  OWNERS
Labels: approved, lgtm

#173 Bug 1986829: metrics: use client cert auth for metrics scraping
  manifests/0000_90_service-ca-operator_03_servicemonitor.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm
